language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library SdFat
  - arduino --install-library ESPAsyncWebServer
  - arduino --install-library ESPAsyncTCP
  - arduino --install-library ESPAsyncWiFiManager
  - arduino --install-library Ticker-esp32
  - arduino --install-library AsyncTCP

script:
  # FIXME: How to tell it just to compile my one sketch?
  - build_platform esp8266
  - build_platform esp32
