language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.7"
before_install:
  - source $TRAVIS_BUILD_DIR/install.sh
script:
  - arduino --install-library SdFat
  - arduino --install-library ESPAsyncWebServer
  - arduino --install-library ESPAsyncTCP
  - arduino --install-library ESPAsyncWiFiManager
  - arduino --install-library Ticker-esp32
  - arduino --install-library AsyncTCP
  - build_platform esp8266
  - build_platform esp32
