language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.7"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
  - cd ~/arduino_ide/libraries/
  - git clone https://github.com/me-no-dev/ESPAsyncWebServer
  - git clone -o 991f855 https://github.com/me-no-dev/ESPAsyncTCP
  - git clone -o 6734c16 https://github.com/alanswx/ESPAsyncWiFiManager
  - ( git clone -b 5.x https://github.com/bblanchon/ArduinoJson ; cd ArduinoJson ; git reset --hard ed98ea4 )
  - git clone https://github.com/greiman/SdFat # SD long names support
  - git clone https://github.com/me-no-dev/AsyncTCP # for ESP32
  - cd -
  - build_platform esp8266
  - build_platform esp32
